services:
  mysql:
    image: mysql:8.0
    container_name: gopherai-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "GopherAI"
    ports:
      - "3306:3306"
    volumes:
      - gopherai-mysql-data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis/redis-stack-server:7.2.0-v10
    container_name: gopherai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - gopherai-redis-data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: gopherai-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "root"
      RABBITMQ_DEFAULT_PASS: "123456"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - gopherai-rabbitmq-data:/var/lib/rabbitmq

volumes:
  gopherai-mysql-data:
  gopherai-redis-data:
  gopherai-rabbitmq-data:
